version: '3'
services:
  syslog_sender:
    build: ./
    image: robertcsapo/cisco-dnac-platform-syslog-notifications:local
    ports:
      - '5000:5000'
    environment:
     - SYSLOG_HOST=
     - SYSLOG_PORT=514
     - SYSLOG_PROTOCOL=UDP
    network_mode: bridge
